# This is a basic workflow to help you get started with Actions

name: Autocommit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automatic commit at $(date)'
          branch: main
          force: true
